from global_data_interface.global_data_class import GlobalEconomy, GlobalIndicator, GlobalEconomyGroup, GlobalIndicatorGroup
from global_data_interface.imf_client import IMFClient
from global_data_interface.un_client import UNClient
from global_data_interface.wb_client import WBClient
from global_data_interface.wto_client import WTOClient